# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend-portafolio
provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    DYNAMODB_TABLE: proyectos-${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self.provider.region}:*:table/User-${sls:stage}

# database
resources:
  Resources:
    DynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE} # - User-local
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
